backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"     # Where uploaded images are stored in your repo
public_folder: "/uploads"          # Path your site uses to access them

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
