backend:
  name: github
  repo: pauljenks1984/scott-gobin-photography-web
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
